### ISSUE TITLE
HTml file error

### ISSUE THREAD

**Issue by vatsalmishraa** [ghoshben/sms-bomber-india#2]
Hey buddy shubam awesome app first sms bomber that actually works but whenever i execute python file and enter the number the html file is not compiled and the whole html code comes on my screen. Im usong termux in my android phone and im using python2 sms_bomb.py to run it im 99‰ sure im doing something worng can you tell me what

**Comment by ghoshben** [comment]
I really did not understood what you are trying to say ? no html was used . however use python 3

**Comment by vatsalmishraa** [comment]
![Screenshot_20190330-014835](https://user-images.githubusercontent.com/49005423/55260404-57992a00-528e-11e9-9b55-486cc93975bf.png)
![Screenshot_20190330-014844](https://user-images.githubusercontent.com/49005423/55260409-5b2cb100-528e-11e9-9d5f-b37ab2e6786d.png)

**Comment by vatsalmishraa** [comment]
this is the situation even though im getting messages im also getting this block of code also i tried with python3 its still showing this code

**Comment by ghoshben** [comment]
@vatsallemon  its not ur fault the code is cold and many of the api changed. However I ll update the code If I get Time
